name: langgenius/dify-api

on:
  # 定时任务，每天凌晨 2 点执行
  schedule:
    - cron: '0 2 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Sync images
        run: |
          # 定义镜像列表
          DIFY_IMAGES=(
            "langgenius/dify-api"
          )

          for IMAGE in "${DIFY_IMAGES[@]}"; do
            # 拉取镜像
            docker pull "$IMAGE"

            # 为镜像添加阿里云镜像仓库的标签
            ALIYUN_IMAGE="${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/${IMAGE}"
            docker tag "$IMAGE" "$ALIYUN_IMAGE"

            # 推送镜像到阿里云镜像仓库
            docker push "$ALIYUN_IMAGE"
          done
